### ISSUE TITLE
Automapper not displaying maps correctly 

### ISSUE THREAD

**Issue by arc118** [GenieClient/genie3#5] opened 2021-12-29 21:32 UTC
Maps are being displayed off center with most recent build (lint clean-up). No way to re-center or scroll maps that are off center in Automapper window. 

![automapper-offcenter](https://user-images.githubusercontent.com/96793326/147704833-05066c7c-8e64-4a63-b156-c112b860290a.png)

**Comment by scottr1634** [comment] 2021-12-29 21:49
I can confirm this one as well.

**Comment by hubConnect** [comment] 2021-12-30 16:52
Seems like the issue is two-fold. The original offsets of the map that are calculated are pushing the map beyond the dimensions of the panel, and the panel is not detecting the content in FlickerFreePanel is larger and enabling the scrollbars.

**Comment by scottr1634** [comment] 2021-12-30 20:43
Addressed in https://github.com/GenieClient/genie3/pull/16

**Closed by scottr1634** 2021-12-30 20:43 UTC
